### ISSUE TITLE
Task: 给项目依赖升个级

### ISSUE THREAD

**Issue by Shareong** [WeBankFinTech/WeCross#349]
把WeCross的各个项目的依赖更新到同版本的最新版本吧！修改`build.gradle`文件的`dependencies`即可。
例如，将
```
compile 'org.springframework.boot:spring-boot-starter-log4j2:2.1.13.RELEASE'
```
修改为
```
compile 'org.springframework.boot:spring-boot-starter-log4j2:2.1.16.RELEASE'
```
项目列表

- [x] [WeCross-Router](https://github.com/WeBankFinTech/WeCross)

- [x] [WeCross-BCOS-Stub](https://github.com/WeBankFinTech/WeCross-BCOS2-Stub)

- [x] [WeCross-Fabric-Stub](https://github.com/WeBankFinTech/WeCross-Fabric1-Stub)

- [x] [WeCross-Console](https://github.com/WeBankFinTech/WeCross-Console)

- [x] [WeCross-Java-Sdk](https://github.com/WeBankFinTech/WeCross-Java-SDK)

**Comment by JimmyShi22** [comment]
#352

**Comment by Shareong** [comment]
- [x] [WeCross-Router](https://github.com/WeBankFinTech/WeCross) done by #354 @RobinLG

**Comment by Shareong** [comment]
- [x] [WeCross-Console](https://github.com/WeBankFinTech/WeCross-Console) done by [#100](https://github.com/WeBankFinTech/WeCross-Console/pull/100) @RobinLG

**Comment by Shareong** [comment]
- [x] [WeCross-Java-SDK](https://github.com/WeBankFinTech/WeCross-Java-SDK) done by [#93](https://github.com/WeBankFinTech/WeCross-Java-SDK/pull/93) @RobinLG

**Comment by Shareong** [comment]
- [x] [WeCross-Fabric1-Stub](https://github.com/WeBankFinTech/WeCross-Fabric1-Stub) done by [#89](https://github.com/WeBankFinTech/WeCross-Fabric1-Stub/pull/89) @RobinLG
